#!/usr/bin/env sh

# Use tiling please :)
#yabai -m config layout bsp
#yabai -m config window_shadow float

# Focus follows mouse and reverse
#yabai -m config mouse_follows_focus no
#yabai -m config focus_follows_mouse autoraise

# Where to place windows?
yabai -m config window_origin_display default
yabai -m config window_placement second_child

# Split in halves, do not try to be smart
yabai -m config split_ratio 0.50
yabai -m config split_type auto
yabai -m config auto_balance off

# Disable animations
yabai -m config window_animation_duration 0.0
yabai -m config window_animation_frame_rate 120
yabai -m config window_topmost off
yabai -m config window_opacity off

# Moving and resizing windows with the mouse
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# Paddings for aesthetics
yabai -m config top_padding 5
yabai -m config bottom_padding 5
yabai -m config left_padding 5
yabai -m config right_padding 5
yabai -m config window_gap 5

yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"
yabai -m signal --add event=display_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# Seems like a good idea but really isn't
# yabai -m signal --add event=window_destroyed action="yabai -m window --focus recent"

# Disable for specific apps
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^balenaEtcher$" manage=off
yabai -m rule --add app="^Creative Cloud$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add title="Preferences$" manage=off
yabai -m rule --add title="Settings$" manage=off

# Dock injection
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
