#!/usr/bin/env bash

# Don't put duplicate lines or lines starting with space in the history
HISTCONTROL=ignoreboth
shopt -s histappend

# Exclude these commands from history
HISTIGNORE="ls:exit:\:q:pwd:clear:[ \t]*"

# Check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Better autocomplete for doas
complete -cf doas

if [ "$TERM" = "linux" ]; then
  # NO ANNOYING BEEPS PLEASE!!
  setterm -blength 0
  clear
fi 

# Nicer prompt
PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

source ~/config/env
source ~/config/aliases
source ~/config/profile

# Plugins

. "$ASDF_DIR/asdf.sh"
#eval "$(starship init bash)"

