#!/usr/bin/env bash

# Don't put duplicate lines or lines starting with space in the history,
# and don't overwrite existing history.
HISTCONTROL=ignoreboth
shopt -s histappend

# Check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Nicer prompt
PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

source ~/config/env
source ~/config/aliases
source ~/config/profile

