#!/bin/sh -eu
# Shamelessly stolen from Drew DeVault
# https://git.sr.ht/~sircmpwn/dotfiles/tree/master/item/.config/git/hooks/pre-commit

failed=""

format() {
  for file in $(git diff --cached --name-only --diff-filter=ACM | grep "\.$1$"); do
	  output="$("$2" "$file" 2>&1 || echo "syntax error")"
	  if [ "$output" != "" ]; then
		  failed="${failed}formatting failed on $file\n"
	  fi
  done
}

format "exs?" "mix format"
format "go" "gofmt -l"

if [ "$failed" != "" ]; then
	echo -e "$failed"
	printf "Ignore? [y/N] "
	read yn </dev/tty
	if [ "$yn" != "y" ]; then
		exit 1
	fi
fi

git_dir="$(git rev-parse --git-dir)"
if [ -x "$git_dir/hooks/pre-commit" ]; then
	exec "$git_dir/hooks/pre-commit"
fi

