#!/usr/bin/env bash
# Stolen from https://alexwlchan.net/2026/no-main-hook/

set -o errexit
set -o nounset

branch="$(git rev-parse --abbrev-ref HEAD)"
root="$(git rev-parse --show-toplevel)"
override="$(git rev-parse --git-path override-master)"

case "/$root/" in
  */qdentity/*)
    case "$branch" in
      master|main|trunk)
        if [ ! -e "$override" ]; then
          echo "You can't commit directly to $branch"
          exit 1
        fi
        ;;
    esac
    ;;
esac
