#!/bin/sh -eu

has() {
  [ -e Bakefile ] && bake help | grep "$1" -q
}

if has deploy && prompt -n "Deploy changes?"; then
  if has build; then
    bake && bake deploy
  else
    bake deploy
  fi
fi

