#!/usr/bin/env bash
# Stolen from https://alexwlchan.net/2026/no-main-hook/

set -o errexit
set -o nounset

branch="$(git rev-parse --abbrev-ref HEAD)"
root="$(git rev-parse --show-toplevel)"

case "/$root/" in
  */qdentity/*)
    if [ "$branch" = 'master' ]; then
      echo "You can't commit directly to master"
      exit 1
    fi
    ;;
esac
